import Head from 'next/head';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Multisite</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="../public/favicon.ico" />
      </Head>
      <main>
        <div className="homeContainer">
          <h3 className="title">Cайты:</h3>
          <div className="links">
            <Link href="/formaggi">Formaggi</Link>
            <Link href="/koko">KOKO</Link>
            <Link href="/rombaba">Кондитерская РОМБАБА</Link>
          </div>
        </div>
      </main>
    </div>
  );
}
